name: Generate Sitemap

on:
  push:
    branches:
      - main
  workflow_dispatch:  # позволяет запускать вручную

jobs:
  generate-sitemap:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # получаем всю историю для правильной работы

      - name: Generate sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: https://parglbibl.ru/
          exclude-paths: >
            privacy.html
            sitemap.html
            yandex_561d16c6c04cad44.html
          include-robots-txt: false
          robots-txt-path: robots.txt
          verbose: true

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Action
          author_email: actions@github.com
          message: 'Автоматическое обновление карты сайта'
          add: 'sitemap.xml'
          push: true